### ISSUE TITLE
What's about invoice

### ISSUE THREAD

**Issue by wesley974** [emmannweb/eshopappltd#1]
Hello,

Does a client can download his invoice using the platform?

Cheers,

/Wesley

**Comment by emmannweb** [comment]
Hi Wesley, it's a good point but i did not implement it yet.

**Comment by wesley974** [comment]
Let's go :)

**Comment by emmannweb** [comment]
:) okay. currently i'm working on a big project, when i have more free time i'll try to add it definitely.
